export { SYLLABUS_QUERY, ANNOUNCEMENT_QUERY ,GRADE_QUERY,FILE_QUERY} from './queries';
export { LOGIN_MUTATION, CREATE_USER_MUTATION, CREATE_SYLLABUS_MUTATION, CREATE_FILE_MUTATION, CREATE_ANNOUNCEMENT_MUTATION, CREATE_GRADE_MUTATION} from './mutations';
