export {
  INFO_QUERY,
  SYLLABUS_QUERY,
  ANNOUNCEMENT_QUERY,
  GRADE_QUERY,
  FILE_QUERY,
  CHATBOX_QUERY,
  CHATBOX_OF_USER_QUERY,
  HW_QUERY,
  QUIZ_QUERY,
} from "./queries";
export {
  CREATE_INFO_MUTATION,
  LOGIN_MUTATION,
  CREATE_USER_MUTATION,
  CREATE_SYLLABUS_MUTATION,
  CREATE_FILE_MUTATION,
  CREATE_ANNOUNCEMENT_MUTATION,
  CREATE_GRADE_MUTATION,
  CREATE_CHATBOX_MUTATION,
  CREATE_MESSAGE_MUTATION,
  CREATE_HW_MUTATION,
  PINMSG_MUTATION,
} from "./mutations";
export {
  MESSAGE_SUBSCRIPTION,
  ANNOUNCEMENT_SUBSCRIPTION,
  SYLLABUS_SUBSCRIPTION,
  GRADE_SUBSCRIPTION,
  FILE_SUBSCRIPTION,
  HW_SUBSCRIPTION,
  CHATBOXLIST_SUBSCRIPTION,
} from "./subscriptions";
