export {
  INFO_QUERY,
  SYLLABUS_QUERY,
  ANNOUNCEMENT_QUERY,
  GRADE_QUERY,
  CHATBOX_QUERY,
} from "./queries";
export {
  CREATE_INFO_MUTATION,
  LOGIN_MUTATION,
  CREATE_USER_MUTATION,
  CREATE_SYLLABUS_MUTATION,
  CREATE_FILE_MUTATION,
  CREATE_ANNOUNCEMENT_MUTATION,
  CREATE_GRADE_MUTATION,
  CREATE_CHATBOX_MUTATION,
  CREATE_MESSAGE_MUTATION,
} from "./mutations";
export { MESSAGE_SUBSCRIPTION } from "./subscriptions";
